<a href="https://colab.research.google.com/github/sharathbantwal/hello-world/blob/master/firstnotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import time
import torch
import torchvision
import numpy as np

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")



shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")
print("Sleeping")
time.sleep(1) # sleep for a while; interrupt me!
print("Done Sleeping")

tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")


tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(tensor, "\n")

tensor.add_(5)
print(tensor)

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

 = np.ones(5)
t = torch.from_numpy(n)


np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5498, 0.7914],
        [0.9746, 0.6417]]) 

Random Tensor: 
 tensor([[0.7137, 0.6785, 0.3075],
        [0.1849, 0.1346, 0.2881]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Sleeping
Done Sleeping
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
tensor @ tensor.T 
 tensor([[1.3699, 1.0345, 1.1117],
        [1.0345, 1.8209, 1.4321],
        [1.1117, 1.4321, 1.5738]])
tensor.matmul(tensor.T) 
 tensor([[1.3699, 1.0345, 1.1117],
        [1.0345, 1.8209, 1.4321],
        [1.1117, 1.4321, 1.5738]]) 

tensor.mul(tensor) 
 tensor([[0.3829, 0.0010, 0.3371, 0.6488],
        [0.8394, 0.7316, 0.1993, 0.0505],
        [0.7900, 0.0685, 0.7089, 0.0064]]) 

tensor * tensor 
 tensor([[0.3829, 0.0010, 0.3371, 0.6488],
        [0.8394, 0.7316, 0.1993, 0.0505],
        [0.7900, 0.0685, 0.7089, 0.0