<a href="https://colab.research.google.com/github/sharathbantwal/hello-world/blob/master/firstnotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import time
import torch
import torchvision

shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")
print("Sleeping")
time.sleep(3) # sleep for a while; interrupt me!
print("Done Sleeping")


Random Tensor: 
 tensor([[0.4398, 0.3427, 0.9994],
        [0.7434, 0.7328, 0.2841]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Sleeping
Done Sleeping
